language: node_js
node_js:
  - "8"
install:
  - yarn
script:
  - npm t
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - node deploy.js
cache: yarn
deploy:
  provider: npm
  email: rodrigonehring@hotmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
