language: node_js
node_js:
  - "8"
install:
  - yarn
script:
  - npm t
cache: yarn
deploy:
  provider: npm
  email: rodrigonehring@hotmail.com
  api_key: $NPM_TOKEN
  script: 'node deploy.js'
  skip_cleanup: true
  on:
    tags: true
